# Generated by Django 3.1.3 on 2020-12-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_article_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='email',
            new_name='cont_art',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='source',
        ),
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.EmailField(default='zdjeice', max_length=1000),
            preserve_default=False,
        ),
    ]
